In [1]:
import pandas as pd

In [7]:
columns = ['target','ids','date','flag','user','text']

df = pd.read_csv("training.1600000.processed.noemoticon.csv",encoding='ISO-8859-1', names=columns)

In [9]:
df.sample(6)

,target,ids,date,flag,user,text
1191295,4,1983863429,Sun May 31 13:59:06 PDT 2009,NO_QUERY,TayDol,there was alot of hot guys at save mart today ...
190593,0,1969394025,Fri May 29 23:54:01 PDT 2009,NO_QUERY,helen_lo,@libertygrrrl I twied to join yr twibe but jus...
218562,0,1976198092,Sat May 30 16:48:06 PDT 2009,NO_QUERY,HeyyAnthony,- I want irissa back http://tumblr.com/xpn1wrj48
140397,0,1881027628,Fri May 22 03:20:57 PDT 2009,NO_QUERY,dscoo,citrus-extract tastes no good
1410191,4,2056227250,Sat Jun 06 10:45:32 PDT 2009,NO_QUERY,lauraafreemann,is excited for hails tonight
444379,0,2067818727,Sun Jun 07 13:00:50 PDT 2009,NO_QUERY,ricottapark,broke down and cleaned tub without aid of topl...

In [10]:
df.isna().sum()

target    0
ids       0
date      0
flag      0
user      0
text      0
dtype: int64

In [11]:
df['target'].unique()

array([0, 4], dtype=int64)

In [12]:
data=df[['text','target']]

In [13]:
data['target'] = data['target'].replace(4,1)

C:\Users\hwi\AppData\Local\Temp\ipykernel_10872\2499609609.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['target'] = data['target'].replace(4,1)

In [14]:
data

                                                      text  target
0        @switchfoot http://twitpic.com/2y1zl - Awww, t...       0
1        is upset that he can't update his Facebook by ...       0
2        @Kenichan I dived many times for the ball. Man...       0
3          my whole body feels itchy and like its on fire        0
4        @nationwideclass no, it's not behaving at all....       0
...                                                    ...     ...
1599995  Just woke up. Having no school is the best fee...       1
1599996  TheWDB.com - Very cool to hear old Walt interv...       1
1599997  Are you ready for your MoJo Makeover? Ask me f...       1
1599998  Happy 38th Birthday to my boo of alll time!!! ...       1
1599999  happy #charitytuesday @theNSPCC @SparksCharity...       1

[1600000 rows x 2 columns]

In [15]:
data_p = data[data['target'] == 1]
data_n = data[data['target'] == 0]
data_p = data_p.iloc[:int(20000)]
data_n = data_n.iloc[:int(20000)]
df = pd.concat([data_p, data_n])
df.shape

(40000, 2)

In [17]:
df['text']=df['text'].str.lower()
df.head()

                                                     text  target
800000       i love @health4uandpets u guys r the best!!        1
800001  im meeting up with one of my besties tonight! ...       1
800002  @darealsunisakim thanks for the twitter add, s...       1
800003  being sick can be really cheap when it hurts t...       1
800004    @lovesbrooklyn2 he has that effect on everyone        1

In [18]:
stopwordlist = ['a', 'about', 'above', 'after', 'again', 'ain', 'all', 'am', 'an',
             'and','any','are', 'as', 'at', 'be', 'because', 'been', 'before',
             'being', 'below', 'between','both', 'by', 'can', 'd', 'did', 'do',
             'does', 'doing', 'down', 'during', 'each','few', 'for', 'from',
             'further', 'had', 'has', 'have', 'having', 'he', 'her', 'here',
             'hers', 'herself', 'him', 'himself', 'his', 'how', 'i', 'if', 'in',
             'into','is', 'it', 'its', 'itself', 'just', 'll', 'm', 'ma',
             'me', 'more', 'most','my', 'myself', 'now', 'o', 'of', 'on', 'once',
             'only', 'or', 'other', 'our', 'ours','ourselves', 'out', 'own', 're','s', 'same', 'she', "shes", 'should', "shouldve",'so', 'some', 'such',
             't', 'than', 'that', "thatll", 'the', 'their', 'theirs', 'them',
             'themselves', 'then', 'there', 'these', 'they', 'this', 'those',
             'through', 'to', 'too','under', 'until', 'up', 've', 'very', 'was',
             'we', 'were', 'what', 'when', 'where','which','while', 'who', 'whom',
             'why', 'will', 'with', 'won', 'y', 'you', "youd","youll", "youre",
             "youve", 'your', 'yours', 'yourself', 'yourselves']

In [21]:
from nltk.corpus import stopwords

def remove_stopwords(text):
    new_text = []
    
    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [22]:
df['text'] = df['text'].apply(remove_stopwords)